# Generated by Django 3.2 on 2021-05-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='credit_card_expiry_month',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='credit_card_expiry_year',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='credit_card_holder',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='credit_card_number',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='pvc',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
