# Generated by Django 3.2 on 2021-05-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210513_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='street_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='country',
            field=models.CharField(default='Iceland', max_length=80),
            preserve_default=False,
        ),
    ]
