# Generated by Django 3.2 on 2021-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210513_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(blank=True),
        ),
    ]
