# Generated by Django 3.2 on 2021-05-14 10:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
