# Generated by Django 3.2 on 2021-05-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_country'),
        ('orders', '0006_alter_orders_total_price'),
    ]

    operations = [
    ]
