# Generated by Django 3.2 on 2021-05-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_merge_20210514_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pvc',
            new_name='cvc',
        ),
    ]
