# Generated by Django 3.2 on 2021-05-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_house_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordered_product',
        ),
    ]
